"""updated

Revision ID: 554c38cf3d4d
Revises: 
Create Date: 2024-04-18 07:04:21.120709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554c38cf3d4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
